version: '2'
services:
  web:
    build: ./docker
    image: culturagovbr/salic-web:1.5
    container_name: salic-web
    ports:
     - "80:80"
     - "9000"
    volumes:
     - ./app:/var/www/salic
     - ./app/public/txt:/var/www/salic/public/txt/
     - ./app/public/plenaria:/var/www/salic/public/plenaria/
    environment:
    #- APPLICATION_ENV=production
     - APPLICATION_ENV=development
     - GIT_BRANCH=develop
     - GIT_REPOSITORY=https://github.com/culturagovbr/salic-minc